In [1]:
import tensorflow as tf

In [2]:
import numpy as np

In [3]:
tf.__version__

'2.11.0'

<h1>  1. tensor </h1>

<h3> 텐서 : 다차원 numpy array(넘피 배열), 데이터럴 위한 컨테이너, 보통 차원이라고 부름

rank, shape, types

<h4> 스칼라(0D)

In [4]:
a = tf.constant(12) # 3 Dimension

In [5]:
a.ndim # rank

0

In [6]:
a

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [7]:
a.shape # scalar

TensorShape([])

In [8]:
a.numpy()

12

<h4> 벡터(1D)

In [9]:
a = tf.constant([1,2,3]) # 1Dimension

In [10]:
a.ndim

1

In [11]:
a

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [12]:
a.shape

TensorShape([3])

In [13]:
# tf to numpy

In [14]:
a1 = a.numpy()

In [15]:
a1

array([1, 2, 3])

In [16]:
# numpy to tf

In [17]:
b = [1,2,3,4]

In [18]:
b = np.array(b)

In [19]:
b

array([1, 2, 3, 4])

In [20]:
b.ndim

1

In [21]:
b1 = tf.constant(b, dtype=np.int32) # 2Dimension

In [22]:
b1

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4])>

<h4> 행렬(2D)

In [23]:
a = tf.constant(([1,2,3],[2, 2, 3]), dtype=np.int32) # 2Dimension

In [24]:
a.ndim

2

In [25]:
a.shape

TensorShape([2, 3])

<h4> 라. 텐서크기변환

In [26]:
a = tf.constant([1, 2, 3, 4, 5, 6], shape=[2, 3]) #2 Dimension

In [27]:
b = tf.reshape(a, [6,1])

In [28]:
b.numpy()

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [29]:
b.ndim

2

In [30]:
b.shape

TensorShape([6, 1])

<h4> 3D텐서

In [31]:
a = tf.constant(([[[1,2,3],[2, 2, 3], [4,5,3]]]), dtype=np.int32) # 3Dimension
a

<tf.Tensor: shape=(1, 3, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [2, 2, 3],
        [4, 5, 3]]])>

In [32]:
a.ndim

3

In [33]:
a.shape

TensorShape([1, 3, 3])

<h4> 텐서 변환

In [34]:
a = tf.constant(np.arange(1, 13, dtype=np.int32), shape=[2, 2, 3]) # 3 Dimension

In [35]:
a # 2*3이 2개 있다.

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])>

In [36]:
a.ndim

3

In [37]:
a1 = tf.reshape(a, [4,3])

In [38]:
a1

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])>

In [39]:
a1.ndim

2

In [40]:
b = tf.constant(np.arange(13, 25, dtype=np.int32),
                shape=[2, 3, 2])

In [41]:
b

<tf.Tensor: shape=(2, 3, 2), dtype=int32, numpy=
array([[[13, 14],
        [15, 16],
        [17, 18]],

       [[19, 20],
        [21, 22],
        [23, 24]]])>

In [42]:
b.ndim

3

In [43]:
b.shape

TensorShape([2, 3, 2])

<h1>  2. 텐서연산(tensor operation)

<h4> 가. 원소별 연산

In [44]:
x = tf.constant([1, 2, 3, 4, 5, 6], shape=[2, 3]) #2 Dimension

In [45]:
x

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [46]:
y = tf.constant([1, 2, 3, 4, 5, 6], shape=[2, 3]) #2 Dimension

In [47]:
y

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [48]:
tf.math.multiply(x,y)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 1,  4,  9],
       [16, 25, 36]])>

In [49]:
tf.math.add(x,y)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 2,  4,  6],
       [ 8, 10, 12]])>

In [50]:
tf.math.divide(x,y)

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]])>

In [51]:
tf.math.subtract(x,y)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0]])>

<h4> 나. 브로드캐스팅

In [52]:
x = tf.constant([1, 2, 3, 4, 5, 6], shape=[2, 3]) #2 Dimension

In [53]:
x

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [54]:
x + 1

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[2, 3, 4],
       [5, 6, 7]])>

In [55]:
x * 2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 2,  4,  6],
       [ 8, 10, 12]])>

<h4> 다. 텐서점곱(tensor product)

In [62]:
a = tf.constant([1, 2, 3, 4, 5, 6], shape=[2, 3]) #2 Dimension
a

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [64]:
b = tf.constant([1, 2, 3, 4, 5, 6], shape=[3, 2]) #2 Dimension
b

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>

In [65]:
c = tf.matmul(a, b)

In [66]:
c

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[22, 28],
       [49, 64]])>

In [67]:
a @ b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[22, 28],
       [49, 64]])>

In [68]:
np.dot(a, b)

array([[22, 28],
       [49, 64]])