In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

In [2]:
tf.__version__

'2.11.0'

<h1>  tf.GradientTape : </h1>
    
    Record operations for automatic differentiation.

In [3]:
# Now if you want to take derivatives of this function with respec to w1 and w2:

$$
z = 3w1^2 + 2w1 w2 \\
\frac{\partial{z}}{\partial{w1}} = 6w1 + 2w2 \\
\frac{\partial{z}}{\partial{w2}} = 2w1
$$

In [4]:
def f(w1, w2):
     return 3 * w1 ** 2 + 2 * w1 * w2

In [17]:
w1, w2 = tf.Variable(1.), tf.Variable(1.)

In [18]:
w1

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.0>

In [19]:
with tf.GradientTape() as tape:
    z = f(w1, w2)

gradients = tape.gradient(z, [w1, w2])

In [20]:
# w1, w2가 주어졌을때 z 함수의 1차 미분값

In [21]:
gradients # gradient(기울기) * w

[<tf.Tensor: shape=(), dtype=float32, numpy=8.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=2.0>]

In [22]:
z.numpy()

5.0

In [23]:
x = tf.constant(2.0)


In [24]:
with tf.GradientTape() as t:
    t.watch(x) # x를 gradient tape에 지정
    y = x**3
    dy_dx = t.gradient(y, x)


In [25]:
print(dy_dx)

tf.Tensor(12.0, shape=(), dtype=float32)


<h2>  2. assign_sub

In [29]:
# A.assign_sub(B)
# A = A-B
# A -= B
# A.assign_add(B)
# A = A+ B
# A += B


In [30]:
x = tf.Variable(tf.zeros((2, 1)))
y = tf.Variable(tf.ones((2, 1)))

In [31]:
x.numpy()

array([[0.],
       [0.]], dtype=float32)

In [32]:
y.numpy()

array([[1.],
       [1.]], dtype=float32)

In [33]:
x.assign_sub(y)

<tf.Variable 'UnreadVariable' shape=(2, 1) dtype=float32, numpy=
array([[-1.],
       [-1.]], dtype=float32)>

In [34]:
x.assign_add(y)

<tf.Variable 'UnreadVariable' shape=(2, 1) dtype=float32, numpy=
array([[0.],
       [0.]], dtype=float32)>