## 분석에 필요한 패키지

In [1]:
import numpy as np 
import pandas as pd
import statsmodels.api as sm
from statsmodels.formula.api import ols

In [6]:
df = pd.read_csv("education2020.csv", index_col=0)

In [7]:
df.head()

year metro        id  sex  age  number  education  marriage   asset   debt  \
0  2020    G1  10000112    1   34       3          6         2  112000  54500   
1  2020    G1  10000132    2   45       2          8         2   42500  17500   
2  2020    G1  10000162    2   73       1          2         3    5712      0   
3  2020    G1  10000182    1   58       2          4         2   14870      0   
4  2020    G1  10000192    2   27       1          4         1     814      0   

   income  income_d industry job  house  education_year  
0    6593      4599        F   3      2              16  
1   17720     15257        J   2      3              21  
2     908       725        T   4      2               6  
3    2748      2431        C   5      2              12  
4    1015       893        R   2      3              12

In [8]:
df1 = df[['income', 'education_year']]

In [10]:
df1.tail()

income  education_year
18059     179              16
18060   15454              16
18061   15098              16
18062    9114              18
18063    7857              16

In [11]:
edu_model = ols("income ~ education_year", data=df1).fit()

In [12]:
print(edu_model.summary())

                            OLS Regression Results                            
Dep. Variable:                 income   R-squared:                       0.164
Model:                            OLS   Adj. R-squared:                  0.164
Method:                 Least Squares   F-statistic:                     3535.
Date:                Mon, 13 Feb 2023   Prob (F-statistic):               0.00
Time:                        16:07:26   Log-Likelihood:            -1.7980e+05
No. Observations:               18064   AIC:                         3.596e+05
Df Residuals:                   18062   BIC:                         3.596e+05
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                     coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------
Intercept       -463.3069    107.117     -4.

### 1. 기울기를 구하여라

$$ \Large
\Large \hat{\beta} = (X'X)^{-1}  X'y \\
$$

In [13]:
edu = df1[['education_year']]

In [14]:
X = edu.values

In [23]:
ones = np.ones(X.shape[0])

In [24]:
X_mat=np.column_stack((ones, X))

In [25]:
X_mat

array([[ 1., 16.],
       [ 1., 21.],
       [ 1.,  6.],
       ...,
       [ 1., 16.],
       [ 1., 18.],
       [ 1., 16.]])

In [19]:
# X_mat=np.vstack((np.ones(X.shape[0]), X))

In [26]:
Y = df1['income'].values

In [27]:
Y.shape

(18064,)

In [28]:
beta_hat = np.linalg.inv(X_mat.T.dot(X_mat)).dot(X_mat.T).dot(Y)

In [29]:
np.set_printoptions(precision=4)
np.set_printoptions(suppress=True)

In [30]:
beta_hat.round(4)

array([-463.3069,  507.3283])

In [31]:
beta_hat = np.linalg.inv(X_mat.T @ X_mat) @ (X_mat.T) @ Y

In [32]:
beta_hat.round(4)

array([-463.3069,  507.3283])

## 2. 계수값의 표준오차를 구하여라

$ \Large
\Large  E[\hat{\sigma}^2] = \sigma^2 = \frac{\hat{e}'\hat{e}}{T-K}
$

$ \Large
Cov(\hat{\beta}|X) = \sigma^2 (X'X)^{-1} \\
$

In [33]:
X_mat.shape

(18064, 2)

In [34]:
beta_hat.shape

(2,)

In [35]:
Y_fitted = X_mat @ beta_hat

In [36]:
Y_fitted

array([ 7653.9457, 10190.5872,  2580.6628, ...,  7653.9457,  8668.6023,
        7653.9457])

In [37]:
Y_fitted.shape

(18064,)

In [38]:
e = Y - Y_fitted

In [39]:
e

array([-1060.9457,  7529.4128, -1672.6628, ...,  7444.0543,   445.3977,
         203.0543])

In [40]:
e.shape

(18064,)

In [41]:
e.T @ e

467577445692.8429

In [42]:
n  = len(e)

In [43]:
k = beta_hat.shape[0]

In [44]:
k

2

In [45]:
sigma_hat2 = (e.T @ e) / (n-k)

In [46]:
sigma_hat2.round(2)

25887357.2

In [47]:
XtX_Inv = np.linalg.inv(X_mat.T @ X_mat) 

In [48]:
XtX_Inv

array([[ 0.0004, -0.    ],
       [-0.    ,  0.    ]])

In [49]:
cov = sigma_hat2 * XtX_Inv

In [50]:
cov

array([[11473.9714,  -854.9861],
       [ -854.9861,    72.8025]])

In [51]:
se = np.sqrt(cov)

C:\Users\OWNER\AppData\Local\Temp\ipykernel_7820\4019523673.py:1: RuntimeWarning: invalid value encountered in sqrt
  se = np.sqrt(cov)


In [52]:
se

array([[107.1166,      nan],
       [     nan,   8.5324]])

## 3. 계수값의 신뢰구간 및 t값을 구합니다.

In [53]:
# 신뢰구간"

In [54]:
beta_hat.shape

(2,)

In [55]:
se1 = np.zeros(k)

In [56]:
se1

array([0., 0.])

In [57]:
se1.shape

(2,)

In [58]:
se1[0,]= se[0,0]

In [59]:
se1

array([107.1166,   0.    ])

In [60]:
se1[1,]= se[1,1]

In [61]:
se1

array([107.1166,   8.5324])

In [62]:
# for 문

In [63]:
se2 = np.zeros(k)

In [64]:
for i in range(k):
    se2[i,]= se[i,i]
    

In [65]:
se2

array([107.1166,   8.5324])

In [66]:
beta_hat

array([-463.3069,  507.3283])

In [67]:
lb = beta_hat -  2 * se1
hb = beta_hat +  2 * se1

In [68]:
lb.round(2)

array([-677.54,  490.26])

In [69]:
hb.round(2)

array([-249.07,  524.39])

In [70]:
hb.shape

(2,)

In [71]:
bound = np.column_stack((lb, hb))

In [72]:
bound.round(2)

array([[-677.54, -249.07],
       [ 490.26,  524.39]])

In [73]:
# t값

In [74]:
beta_hat

array([-463.3069,  507.3283])

In [75]:
se1

array([107.1166,   8.5324])

In [76]:
t = beta_hat/se1

In [77]:
t.round(3)

array([-4.325, 59.459])

In [78]:
# p값

In [79]:
from scipy import stats
df = len(e)- 2 # 맞는지 확인할 것

In [80]:
df

18062

In [81]:
t[0]

-4.325256782298774

In [82]:
p0 = np.zeros(k)

In [83]:
for i in range(k):
    if t[i] > 0:
        p0[i,] = (1 - stats.t.cdf(t[i],df=df))*2
    else:
        p0[i,] = (stats.t.cdf(t[i],df=df))*2

In [84]:
p0

array([0., 0.])