## 파이썬: 조건문

In [1]:
import pandas as pd
import numpy as np

> #### 비교 연산자
> - **값끼리 비교**해 참/거짓을 판단할때 사용하는 연산자
> - Python 에서 지원하는 비교 연산자는 다음과 같습니다
>
> |비교 연산자|설명|
|:---------|:---|
|A > B|A 가 B 보다 크다|
|A < B|A 가 B 보다 작다|
|A >= B|A 가 B 보다 크거나 같다|
|A <= B|A 가 B 보다 작거나 같다|
|A == B|A 와 B 가 같다|
|A != B&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|A 가 B 와 같지 않다|

if 조건:
    실행코드

if 조건1:  
    실행코드 1  
elif 조건2:  
    실행코드 2  
else:  
    실행코드 3

In [2]:
x = 3
y = 5


In [3]:

if x > y:
    print('x가 y보다 큽니다.')
elif x< y:
    print('x가 y보다 작습니다.')
else:
    print('x와 y는 같습니다.')


x가 y보다 작습니다.


## 멤버연산자

In [4]:
data = [2,4,6,8]

In [5]:
3 in data

False

In [6]:
4 in data

True

> #### 논리 연산자
> - **논리 연산을 이용**해 참/거짓을 판단할때 사용하는 연산자
> - Python 에서 지원하는 논리 연산자는 다음과 같습니다
>
> |논리 연산자|설명|
|:---------|:---|
|A and B|A 와 B 모두 참이다|
|A or B|A 와 B 중 적어도 하나는 참이다|
|not A&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|A 가 거짓일 때 참이다|

In [6]:
x = 2
y = 3

if (x >1) and (y > 1):
    print('x는 1보다 크고 y도 1보다 큽니다.')
elif(x >1) and (y > 5):
    print('x는 1보다 크고 y는 5보다 큽니다.')
else:
    print('x는 1보다 크거나 y는 5보다 크지 않습니다.')

x는 1보다 크고 y도 1보다 큽니다.


In [1]:
data = [2,4,6,8]

In [3]:
3 in data

False

In [4]:
4 in data

True

In [13]:
# numpy array

In [14]:
# numpy.ndarray, mulitidimensional container

In [7]:
# numpy의 array 함수에 list를 넣으면 배열로 변환해준다 

In [7]:
x = np.array([[1, 2, 3], [4, 5, 6]], np.int32)

In [8]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
type(x)

numpy.ndarray

In [11]:
x.shape

(2, 3)

In [12]:
# indexing

In [13]:
x[1,2]

6

In [14]:
#slicing

In [15]:
y = x[:,1]

In [16]:
y

array([2, 5])

In [17]:
#change 

In [18]:
y[0] = 9

In [19]:
y

array([9, 5])

In [20]:
# ex)

In [21]:
n = 5

In [22]:
interval = np.zeros((n,3))

In [23]:
interval

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
interval.shape

(5, 3)

In [25]:
interval[0][0] = 2

In [26]:
interval

array([[2., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [27]:
interval[0][1] = 2

In [28]:
interval

array([[2., 2., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
interval[0][2] = 2

In [30]:
interval

array([[2., 2., 2.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [31]:
interval[n-1][0] = 2

In [32]:
interval

array([[2., 2., 2.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [2., 0., 0.]])